[package]
name = "bevy_fsl_box_frame"
version = "0.1.0"
edition = "2021"
authors = ["Duncan Fairbanks <duncan.fairbanks@fslabs.ca>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5"
bevy_polyline = "0.7"
parry3d = "0.13"

[dependencies.bevy]
version = "0.11"
default-features = false
features = ["bevy_asset", "bevy_pbr"]

[dependencies.bevy_mod_picking]
version = "0.16"
default-features = false

[dependencies.nalgebra]
version = "0.32"
features = ["glam024"]

[[example]]
name = "demo"
path = "examples/demo.rs"
required-features = ["bevy/bevy_winit", "bevy/x11"]
